// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoohkhipdhinpvrqvlyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvb2hraGlwZGhpbnB2cnF2bHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzA2NzUsImV4cCI6MjA1Njg0NjY3NX0.y_luoPoVBLA2D1TpHGo8YXIpz9wqdWRWD9z0e4qHUMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);